### ISSUE TITLE
Import types are unrecognised with Prisma client 3.7 

### ISSUE THREAD

**Issue by arnabtarwani** [hayes/giraphql#255]
I'm trying to import types however, it looks like the types are unrecognized when they're generated. Not sure what the issue is here. 

```import type { Prisma as , BusinessUser as , Session as , Business as , BusinessCategory as , Product as , ProductPriceRange as , ProductCategory as , MoneyV1 as , CountryCode as  } from "/backend/node_modules/.prisma/client";```

```#13 5.505 prisma/__generated__/giraphql-types.ts(1,15): error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.```

**Comment by hayes** [comment]
For anyone else running into this: I assume this was related to using an older version of typescript

**Comment by arnabtarwani** [comment]
> For anyone else running into this: I assume this was related to using an older version of typescript

No, it was due to an older version of the @giraphql/plugin-prisma package - I'd 0.9.0 installed in my machine and when I upgraded it to 0.14.0, it fixed the issue
